### ISSUE TITLE
I can't choose anything in the window that's popping up to get an image

### ISSUE THREAD

**Issue by FantazerYT** [austinvaness/LcdImagePlugin#2]
Every time I press mouse buttons in my game when these windows with image selecting are open, It's getting me thrown out to the desktop. Unusable for me

**Comment by austinvaness** [comment]
You are not supposed to be able to interact with the game while the image selecting popup is open. You have to close it or select an image first

**Comment by FantazerYT** [comment]
i know but i just can't
everytime i click at anything in this popup my game just keeps getting minimized so im getting into my desktop everytime i try to choose an image or even close these windows

> You are not supposed to be able to interact with the game while the image selecting popup is open. You have to close it or select an image first

**Comment by austinvaness** [comment]
Ok I think I understand now. Its minimizing the game when you click the popup after it comes up? Do you have fullscreen display mode on? That could cause this issue and I'm not sure how to fix that

**Comment by FantazerYT** [comment]
it works!
choosing Borderless fullscreen is the way, thank you
